// This file is auto-generated by @hey-api/openapi-ts

export interface ClientOptions {
    baseURL: 'http://localhost:8080' | (string & {});
}

/**
 * Claim input data
 */
export interface ClaimRequestBody {
    /**
     * universal file number
     */
    ufn: string;
    /**
     * client name
     */
    client: string;
    /**
     * claim category
     */
    category?: string;
    /**
     * claim concluded date
     */
    concluded?: string;
    /**
     * fee type
     */
    feeType?: string;
    /**
     * amount claimed
     */
    claimed?: number;
    /**
     * id of the submission this claim links to
     */
    submissionId?: string;
}

export interface ApiErrorResponse {
    /**
     * High-level error type
     */
    title?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * Human-readable explanation
     */
    detail?: string;
    /**
     * Internal error code for machine consumption
     */
    errorCode?: string;
    /**
     * Unique ID for log correlation
     */
    correlationId?: string;
}

export interface Claim {
    id: number;
    /**
     * universal file number
     */
    ufn?: string;
    /**
     * ID of the provider user making the submission
     */
    providerUserId?: string;
    /**
     * client name
     */
    client?: string;
    /**
     * claim category
     */
    category?: string;
    /**
     * claim concluded date
     */
    concluded?: string;
    /**
     * fee type
     */
    feeType?: string;
    /**
     * amount claimed
     */
    claimed?: number;
    /**
     * id of the submission this claim belongs to
     */
    submissionId: string;
}

export interface ClaimPage {
    claims?: Claim[];
    page?: number;
    limit?: number;
    total?: number;
    totalPages?: number;
}

export interface UpdateClaimData {
    body: ClaimRequestBody;
    path: {
        /**
         * ID of the claim to update
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/claims/{id}';
}

export interface UpdateClaimErrors {
    /**
     * **Invalid Request**
     * * **Codes**: `VALIDATION_FAILED`, `BAD_REQUEST`
     * * Occurs when the request payload fails validation or is malformed.
     *
     */
    400: ApiErrorResponse;
    /**
     * **Unauthenticated**
     * * **Codes**: `UNAUTHENTICATED`
     * * Authentication is missing or the provided token is invalid.
     *
     */
    401: ApiErrorResponse;
    /**
     * **Forbidden**
     * * **Codes**: `FORBIDDEN`
     * * The user is authenticated but lacks the required OAuth scopes or permissions.
     *
     */
    403: ApiErrorResponse;
    /**
     * **Not Found**
     * * **Codes**: `NOT_FOUND`
     * * The requested resource (e.g., Claim ID) does not exist.
     *
     */
    404: ApiErrorResponse;
    /**
     * **Conflict**
     * * **Codes**: `CONFLICT`
     * * The request conflicts with the current state of the resource in an upstream system.
     *
     */
    409: ApiErrorResponse;
    /**
     * **Too Many Requests**
     * * **Codes**: `TEMPORARILY_UNAVAILABLE`
     * * An upstream service is currently rate-limiting requests.
     *
     */
    429: ApiErrorResponse;
    /**
     * **Internal Server Error**
     * * **Codes**: `INTERNAL_ERROR`, `SERVICE_ERROR`
     * * An unexpected error occurred within this service.
     *
     */
    500: ApiErrorResponse;
    /**
     * **Upstream Service Error**
     * * **Codes**: `UPSTREAM_ERROR`
     * * A dependent upstream service returned an invalid or error response.
     *
     */
    502: ApiErrorResponse;
    /**
     * **Upstream Timeout**
     * * **Codes**: `UPSTREAM_TIMEOUT`
     * * A dependent upstream service failed to respond within the allowed time.
     *
     */
    504: ApiErrorResponse;
}

export type UpdateClaimError = UpdateClaimErrors[keyof UpdateClaimErrors];

export interface UpdateClaimResponses {
    /**
     * Claim updated successfully
     */
    204: void;
}

export type UpdateClaimResponse = UpdateClaimResponses[keyof UpdateClaimResponses];

export interface GetClaimsData {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
    };
    url: '/api/v1/claims';
}

export interface GetClaimsErrors {
    /**
     * **Invalid Request**
     * * **Codes**: `VALIDATION_FAILED`, `BAD_REQUEST`
     * * Occurs when the request payload fails validation or is malformed.
     *
     */
    400: ApiErrorResponse;
    /**
     * **Unauthenticated**
     * * **Codes**: `UNAUTHENTICATED`
     * * Authentication is missing or the provided token is invalid.
     *
     */
    401: ApiErrorResponse;
    /**
     * **Forbidden**
     * * **Codes**: `FORBIDDEN`
     * * The user is authenticated but lacks the required OAuth scopes or permissions.
     *
     */
    403: ApiErrorResponse;
    /**
     * **Not Found**
     * * **Codes**: `NOT_FOUND`
     * * The requested resource (e.g., Claim ID) does not exist.
     *
     */
    404: ApiErrorResponse;
    /**
     * **Conflict**
     * * **Codes**: `CONFLICT`
     * * The request conflicts with the current state of the resource in an upstream system.
     *
     */
    409: ApiErrorResponse;
    /**
     * **Too Many Requests**
     * * **Codes**: `TEMPORARILY_UNAVAILABLE`
     * * An upstream service is currently rate-limiting requests.
     *
     */
    429: ApiErrorResponse;
    /**
     * **Internal Server Error**
     * * **Codes**: `INTERNAL_ERROR`, `SERVICE_ERROR`
     * * An unexpected error occurred within this service.
     *
     */
    500: ApiErrorResponse;
    /**
     * **Upstream Service Error**
     * * **Codes**: `UPSTREAM_ERROR`
     * * A dependent upstream service returned an invalid or error response.
     *
     */
    502: ApiErrorResponse;
    /**
     * **Upstream Timeout**
     * * **Codes**: `UPSTREAM_TIMEOUT`
     * * A dependent upstream service failed to respond within the allowed time.
     *
     */
    504: ApiErrorResponse;
}

export type GetClaimsError = GetClaimsErrors[keyof GetClaimsErrors];

export interface GetClaimsResponses {
    /**
     * List of claims linked to a provider user
     */
    200: ClaimPage;
}

export type GetClaimsResponse = GetClaimsResponses[keyof GetClaimsResponses];

export interface CreateClaimData {
    body: ClaimRequestBody;
    path?: never;
    query?: never;
    url: '/api/v1/claims';
}

export interface CreateClaimErrors {
    /**
     * **Invalid Request**
     * * **Codes**: `VALIDATION_FAILED`, `BAD_REQUEST`
     * * Occurs when the request payload fails validation or is malformed.
     *
     */
    400: ApiErrorResponse;
    /**
     * **Unauthenticated**
     * * **Codes**: `UNAUTHENTICATED`
     * * Authentication is missing or the provided token is invalid.
     *
     */
    401: ApiErrorResponse;
    /**
     * **Forbidden**
     * * **Codes**: `FORBIDDEN`
     * * The user is authenticated but lacks the required OAuth scopes or permissions.
     *
     */
    403: ApiErrorResponse;
    /**
     * **Not Found**
     * * **Codes**: `NOT_FOUND`
     * * The requested resource (e.g., Claim ID) does not exist.
     *
     */
    404: ApiErrorResponse;
    /**
     * **Conflict**
     * * **Codes**: `CONFLICT`
     * * The request conflicts with the current state of the resource in an upstream system.
     *
     */
    409: ApiErrorResponse;
    /**
     * **Too Many Requests**
     * * **Codes**: `TEMPORARILY_UNAVAILABLE`
     * * An upstream service is currently rate-limiting requests.
     *
     */
    429: ApiErrorResponse;
    /**
     * **Internal Server Error**
     * * **Codes**: `INTERNAL_ERROR`, `SERVICE_ERROR`
     * * An unexpected error occurred within this service.
     *
     */
    500: ApiErrorResponse;
    /**
     * **Upstream Service Error**
     * * **Codes**: `UPSTREAM_ERROR`
     * * A dependent upstream service returned an invalid or error response.
     *
     */
    502: ApiErrorResponse;
    /**
     * **Upstream Timeout**
     * * **Codes**: `UPSTREAM_TIMEOUT`
     * * A dependent upstream service failed to respond within the allowed time.
     *
     */
    504: ApiErrorResponse;
}

export type CreateClaimError = CreateClaimErrors[keyof CreateClaimErrors];

export interface CreateClaimResponses {
    /**
     * Claim created successfully
     */
    201: unknown;
}

export interface DeleteClaimData {
    body?: never;
    path: {
        /**
         * ID of the claim to delete
         */
        claimId: number;
    };
    query?: never;
    url: '/api/v1/claims/{claimId}';
}

export interface DeleteClaimErrors {
    /**
     * **Invalid Request**
     * * **Codes**: `VALIDATION_FAILED`, `BAD_REQUEST`
     * * Occurs when the request payload fails validation or is malformed.
     *
     */
    400: ApiErrorResponse;
    /**
     * **Unauthenticated**
     * * **Codes**: `UNAUTHENTICATED`
     * * Authentication is missing or the provided token is invalid.
     *
     */
    401: ApiErrorResponse;
    /**
     * **Forbidden**
     * * **Codes**: `FORBIDDEN`
     * * The user is authenticated but lacks the required OAuth scopes or permissions.
     *
     */
    403: ApiErrorResponse;
    /**
     * **Not Found**
     * * **Codes**: `NOT_FOUND`
     * * The requested resource (e.g., Claim ID) does not exist.
     *
     */
    404: ApiErrorResponse;
    /**
     * **Conflict**
     * * **Codes**: `CONFLICT`
     * * The request conflicts with the current state of the resource in an upstream system.
     *
     */
    409: ApiErrorResponse;
    /**
     * **Too Many Requests**
     * * **Codes**: `TEMPORARILY_UNAVAILABLE`
     * * An upstream service is currently rate-limiting requests.
     *
     */
    429: ApiErrorResponse;
    /**
     * **Internal Server Error**
     * * **Codes**: `INTERNAL_ERROR`, `SERVICE_ERROR`
     * * An unexpected error occurred within this service.
     *
     */
    500: ApiErrorResponse;
    /**
     * **Upstream Service Error**
     * * **Codes**: `UPSTREAM_ERROR`
     * * A dependent upstream service returned an invalid or error response.
     *
     */
    502: ApiErrorResponse;
    /**
     * **Upstream Timeout**
     * * **Codes**: `UPSTREAM_TIMEOUT`
     * * A dependent upstream service failed to respond within the allowed time.
     *
     */
    504: ApiErrorResponse;
}

export type DeleteClaimError = DeleteClaimErrors[keyof DeleteClaimErrors];

export interface DeleteClaimResponses {
    /**
     * Claim deleted successfully
     */
    204: void;
}

export type DeleteClaimResponse = DeleteClaimResponses[keyof DeleteClaimResponses];

export interface GetClaimData {
    body?: never;
    path: {
        /**
         * ID of the claim to retrieve
         */
        claimId: number;
    };
    query?: never;
    url: '/api/v1/claims/{claimId}';
}

export interface GetClaimErrors {
    /**
     * **Invalid Request**
     * * **Codes**: `VALIDATION_FAILED`, `BAD_REQUEST`
     * * Occurs when the request payload fails validation or is malformed.
     *
     */
    400: ApiErrorResponse;
    /**
     * **Unauthenticated**
     * * **Codes**: `UNAUTHENTICATED`
     * * Authentication is missing or the provided token is invalid.
     *
     */
    401: ApiErrorResponse;
    /**
     * **Forbidden**
     * * **Codes**: `FORBIDDEN`
     * * The user is authenticated but lacks the required OAuth scopes or permissions.
     *
     */
    403: ApiErrorResponse;
    /**
     * **Not Found**
     * * **Codes**: `NOT_FOUND`
     * * The requested resource (e.g., Claim ID) does not exist.
     *
     */
    404: ApiErrorResponse;
    /**
     * **Conflict**
     * * **Codes**: `CONFLICT`
     * * The request conflicts with the current state of the resource in an upstream system.
     *
     */
    409: ApiErrorResponse;
    /**
     * **Too Many Requests**
     * * **Codes**: `TEMPORARILY_UNAVAILABLE`
     * * An upstream service is currently rate-limiting requests.
     *
     */
    429: ApiErrorResponse;
    /**
     * **Internal Server Error**
     * * **Codes**: `INTERNAL_ERROR`, `SERVICE_ERROR`
     * * An unexpected error occurred within this service.
     *
     */
    500: ApiErrorResponse;
    /**
     * **Upstream Service Error**
     * * **Codes**: `UPSTREAM_ERROR`
     * * A dependent upstream service returned an invalid or error response.
     *
     */
    502: ApiErrorResponse;
    /**
     * **Upstream Timeout**
     * * **Codes**: `UPSTREAM_TIMEOUT`
     * * A dependent upstream service failed to respond within the allowed time.
     *
     */
    504: ApiErrorResponse;
}

export type GetClaimError = GetClaimErrors[keyof GetClaimErrors];

export interface GetClaimResponses {
    /**
     * Claim found
     */
    200: Claim;
}

export type GetClaimResponse = GetClaimResponses[keyof GetClaimResponses];
